Revert "[gitmaster]: Reintroduce %find-lag reverted by previous patch"
This reverts commit 8b64bc9c07c0cd912b4a75b748a55310f9728aa2.

This aborts in a really strange way for me right now:
```
RPM build errors:
error: Unterminated (: (
```